### PR TITLE
DRY was missed: depositedCollateral modifier used in testRevertsIfMintAmountBreaksHelthFactor() test

### PR DESCRIPTION
**Pull request by alfheimrShiven**

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Thanks! Looks like there is some conflicts now

**Comment by alfheimrShiven** [comment]
Hey @PatrickAlphaC pulled the latest main branch to resolve it.

**Comment by PatrickAlphaC** [comment]
Screenshot 2023-09-14 at 8 29 00 PM

I'm still seeing this?

**Comment by alfheimrShiven** [comment]
My bad @PatrickAlphaC . I've cleaned it up. Requesting you to review.

**Pull request merged**
