### PR TITLE
Adding in-line config to invariant tests 

### PR DESCRIPTION
**Pull request by fabriziogianni7**
# Description
In this [lesson](https://updraft.cyfrin.io/courses/advanced-foundry/develop-defi-protocol/defi-handler-redeeming-collateral) Patrick mentions the possibility of integrate inline config to make tests fail or don't fail on revert.

I discovered that foundry [now allow this possibility](https://book.getfoundry.sh/reference/config/inline-test-config) 

With this PR I'm just using foundry inline test config to make the `ContinueOnRevert` tests work.

## Demo
See how we have all invariant tests working: some of them have 0 revert and others have some.
Schermata 2024-04-09 alle 09 19 34

## Other things
Additionally,
- I updated Solidity version to 0.8.25 
- I updated version of cyfrin/foundry-devops to 0.1.0

I'm not sure that this updates will be ok in order to merge the PR - I did this because the project couldn't run on my mac otherwise

### CODE REVIEW

**Comment by fabriziogianni7** [comment]
About the error I got with previous version of solidity:
```
solc exited with signal: 6 (SIGABRT)
dyld: Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEEC1Ev
  Referenced from: /Users/fabri/Library/Application Support/svm/0.8.18/solc-0.8.18 (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
  ```
  
  I think foundry get a wrong  0.8.18 for my mac! not sure how to address this

**Comment by PatrickAlphaC** [comment]
Thanks for this! Sorry on my delay here. Wondering, can you address the conflicts? I'd love to merge this.

**Comment by fabriziogianni7** [comment]
@PatrickAlphaC 
I addressed the conflicts and additionally:
- updated solidity version on `ERC20Mock` to 0.8.25;
- `StopOnRevertHandler` had a small error: sometimes it was failing with this error: `cannot overwrite a prank until it is applied at least once` --> [fixed small error in stopOnRevertHandler](https://github.com/Cyfrin/foundry-defi-stablecoin-f23/pull/70/commits/160a8b272c1e94bf5abed37c98629314f3204765) I commented `vm.prank(msg.sender);`. dunno if that was intended tho. 

Please let me know if you have other things to point out! 
Thanks!

**Comment by PatrickAlphaC** [comment]
Thank you!!

https://github.com/Cyfrin/foundry-defi-stablecoin-f23/pull/73

I opened a new pr from your PR to change the solc version back to 0.8.19 - this is great!

**Pull request closed without merging**
